### ISSUE TITLE
Statistics is not displayed when rtt is less than 1 ms.

### ISSUE THREAD

**Issue by icemint0828** [pouriyajamshidi/tcping#10]
There are cases where rtt is less than 1ms, such as when the remote server is exists in a private network.
In this case, statistics is not displayed with enter or signal.

![ss_2022-05-12](https://user-images.githubusercontent.com/89819001/168005577-a1fe2cec-e6e9-4f97-afd9-03e1dfdf6137.png)

I feel that rttResults.hasResults should be based on whether arrLen is greater than 0, not whether accum is not equal to 0.

https://github.com/pouriyajamshidi/tcping/blob/1533ad5d47d30071957516ef7e0ba08707043880/tcping.go#L154-L157

Is it okay if I fix it?

**Comment by pouriyajamshidi** [comment]
If I recall correctly, having all zeros would result in a panic later on down the chain. However, it's been a long time since I've written that part.

You are more than welcome to give it a shot and observe the behavior, if it is working just fine, I don't see any reason why not to fix it.

For some discussions, what would be the medium to reach out to you for a quick chat?

**Comment by icemint0828** [comment]
Hi @pouriyajamshidi , thank you for your thoughtful explanation.

I'll try it out and see how it behaves.

> For some discussions, what would be the medium to reach out to you for a quick chat?

I actually don't have a chat account for OSS:sweat:
If it is very much needed, i will make it, but it may not be right away.

**Comment by pouriyajamshidi** [comment]
Hi @icemint0828 ,

That is fine. I wanted to discuss a few things in an easier way but for the time being, we can continue our discussions here.

Thanks!
