### ISSUE TITLE
Please add "count" and "interval" option

### ISSUE THREAD

**Issue by hackevin** [pouriyajamshidi/tcping#111]
**Describe the solution you'd like**
-c : ping count
-i : interval between ping requests

**Comment by pouriyajamshidi** [comment]
The `-c` or count option has been added and will be available in version 2.0 which is planned to be released soon (hopefully less than two weeks).

The `-i` or interval option is somewhat nonsensical to me since if a TCP connection takes more than a **second**, which on its own is a lifelong then it means there are bigger problems somewhere else. 

@hackevin  Could you please give me an example on how you would like to use the `-i` flag? Or your use case for it. I need to get some context to see if it is worthwhile to invest time there or address other open issues.

**Comment by hackevin** [comment]
Sometimes, if the network is unstable, I'd like to test and sniffer for the failure reason, shorten the interval can reproduce the problem easily.

Thanks a lot.

**Comment by pouriyajamshidi** [comment]
The `-c` flag is now implemented and available in version2 which will be release in a few hours.

For the `-i` option, there was already an open issue at https://github.com/pouriyajamshidi/tcping/issues/7 

It can be tracked there.
