### ISSUE TITLE
Database closure before the appropriate time.

### ISSUE THREAD

**Issue by wizsk** [pouriyajamshidi/tcping#134]
**Describe the bug**
If you press enter while `tcping` is running then the `pritStats` is called.
But When I was writing this db save functionality I overlooked this part and I close the `db` 1st time `database.printStats` is called. 

**To Reproduce:**
1. Run the following command in the terminal:
   ```bash
   tcping example.com 80 --db /tmp/tcping.db
   ```
2. Press the "Enter" key twice.
3. The following output is observed:
   ```bash
   TCPinging example.com on port 80

   Statistics for "example.com" have been saved to "/tmp/tcping.db" in the table "example_com_80_22_45_52_08_20_2023"

   Error while writing stats to the database "/tmp/tcping.db"
   err: sql: database is closed
   exit status 1
   ```
**Issue Resolution:**
To address this issue, it is important to allow the `database.printStats()` function to distinguish between an "Enter" key press and a `ctrl+c` signal.

I looked around the codebase and found 
This fucn handles enter part
https://github.com/pouriyajamshidi/tcping/blob/aafa6f31f6f40c9a1af39567780c70fdeb9c543e/tcping.go#L156C1-L165C2
And this func handles the exit part.
https://github.com/pouriyajamshidi/tcping/blob/aafa6f31f6f40c9a1af39567780c70fdeb9c543e/tcping.go#L145C1-L153C2

**I wanna fix this fast. Please give some feedback.**

**Comment by wizsk** [comment]
hey @pouriyajamshidi 
I will work on it tomorrow.

There should be a global channel or something?
Give some feedback. Sorry for introducing this bug.

**Comment by pouriyajamshidi** [comment]
Hey @wizsk,

oh right, I also missed this during review. Good catch.

First of all, do not worry about it. there is enough time to work on a fix with patience since we have not released the latest changes yet.

My preference is to not touch the logic for enter key detection and signal handler in `tcping.go` for this issue. 

For these matters we have a global shutdown handler here https://github.com/pouriyajamshidi/tcping/blob/aafa6f31f6f40c9a1af39567780c70fdeb9c543e/tcping.go#L186

Inside it we can check if the output is being stored in the DB and if so, we can call the `Close()` on it.
