### ISSUE TITLE
Significant size increase

### ISSUE THREAD

**Issue by God-damnit-all** [pouriyajamshidi/tcping#184]
This isn't really a "bug" (unless it is?) so I'm submitting it as just a generic issue.

I noticed that the binary for tcping on Windows went from ~5.8MB to ~9.1MB, and judging by the download sizes in the release section, it seems there's a similar significant increase on every platform, but for what reason? Is it due to refactoring related to `sqlite`?

**Comment by pouriyajamshidi** [comment]
Thanks for reporting this so **quickly** @ImportTaste 

I am not quite sure what could be the actual cause of it yet. Although, the `sqlite` package seems like a good place to start looking since the rest of the changes are non-package related.

Another thing could be some compiler internal thing that was addressed from 1.21 to 1.21.4

**Comment by pouriyajamshidi** [comment]
Looks like it is because of the `sqlite` package.

```console
5.6M  tcping_before_pureGo_sqlite.exe
8.7M  tcping_latest.exe
```

**Comment by pouriyajamshidi** [comment]
yea, it is quite odd for me as well.

Hopefully we can find a way to somehow reduce the binary size in the future.
