### ISSUE TITLE
Time report is not accurate

### ISSUE THREAD

**Issue by pouriyajamshidi** [pouriyajamshidi/tcping#83]
## Summary

PR https://github.com/pouriyajamshidi/tcping/pull/76 helped tidying up a lot of technical debt surrounding the way we were handling timing and helped standardizing the code. 

However, as a by product, for downtimes that are around a second, we are reporting the time as `0` instead of `1`. Although it is a cosmetic matter, based on the discussion in the aforementioned PR, we decided to pursue those fixes in a sperate issue.

In the image below, we can see:

- `No response received for 0 seconds` showing **0** but should be **1**
- The `from` to `to` appear to be incorrect. They have overlapping values

```text
longest consecutive uptime:   2 seconds from 2023-05-18 22:31:43 to 2023-05-18 22:31:45
longest consecutive downtime: 1 second from 2023-05-18 22:31:43 to 2023-05-18 22:31:44
```

![image](https://github.com/pouriyajamshidi/tcping/assets/54482226/bc42bca7-ccf4-4800-b8a2-0eeaa1448be1)

## How to reproduce

run the program:

```bash
go run . fb.com 443
```

Cause a downtime to the destination and recover after a second:

```bash
sudo iptables -A OUTPUT -d 179.60.195.36 -j DROP; sleep 1; sudo iptables -F
```

**Comment by ravsii** [comment]
Quick investigation on
> No response received for 0 seconds showing 0 but should be 1

As logs show, this functions still uses _actual_ time to calculate downtime.

![image](https://github.com/pouriyajamshidi/tcping/assets/5007271/25d23be0-42e1-4cc3-95be-0e6bff2f2abc)

For a quick fix this will do (I feel like PR is a bit too much for it, since it's not an actual fix as well)

`tcping.go`, `calcTime()`
```go
seconds := duration.Seconds()
if seconds > 0 && seconds < 2 {
	seconds = 1
}
```

Actual problem lies here (it should be using `ongoingUnsuccessfulProbes * time.Second`, or something similar)

https://github.com/pouriyajamshidi/tcping/blob/2839563055a3e76c821d2e7db73901339ff84519/statsprinter.go#L201-L205

Although this could be fixed now, I believe it's better to do when we'll fix hardcoded `time.Second`s, imho.

**Comment by pouriyajamshidi** [comment]
> For a quick fix this will do (I feel like PR is a bit too much for it, since it's not an actual fix as well)

That's a good quick win.

> Although this could be fixed now, I believe it's better to do when we'll fix hardcoded `time.Second`s, imho.

No objections. This issue aims to address that problem (the next release is blocked by this issue).

**Comment by pouriyajamshidi** [comment]
Looks like the longest consecutive downtime is also not displayed at times:

![image](https://github.com/pouriyajamshidi/tcping/assets/54482226/08c2f4bd-ef03-4528-bc8d-d14c8d1021b6)

**Comment by pouriyajamshidi** [comment]
One more odd result:

<img width="758" alt="image" src="https://github.com/pouriyajamshidi/tcping/assets/54482226/043901a9-0901-4b71-a6ad-3e95b8f9073d">
